### ISSUE TITLE
rewrite it in rust

### ISSUE THREAD

**Issue by jozsefsallai** [BosEriko/bos-cli#1]
please :(

**Comment by BosEriko** [comment]
@jozsefsallai https://github.com/BosEriko/bos-cli/tree/general/1566807217/migrate-to-rust

is your comment a reference to my current branch that I'm working on? haha or is it just coincidence?

**Comment by BosEriko** [comment]
Any reason why you said Rust instead of Go?

**Comment by jozsefsallai** [comment]
lmao I didn't even know you were planning on that, I just made this because of the meme: https://transitiontech.ca/random/RIIR

**Comment by BosEriko** [comment]
geezus. I'm following a meme and I'm not aware. xD
